services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    working_dir: /workspace/frontend
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3000:3000" # Nuxt dev server
    volumes:
      - ./frontend:/workspace/frontend:cached
      - node_modules:/workspace/frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    working_dir: /workspace/backend
    command: ["tail", "-f", "/dev/null"]  # Optional: replace with actual dev command
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/workspace/backend
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Database=devdb;Username=devuser;Password=devpassword
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: dotnet-vue-db-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dotnet-vue-redis-1
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
  node_modules:
